name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./backend/gradlew

      - name: Build with Gradle Wrapper
        run: |
          cd ./backend/
          ./gradlew build
        
      - name: Build Docker image
        run: |
          docker build -t my-spring-app .
      
      - name: Tag Docker image
        run: |
          docker tag my-spring-app:latest $ECR_REGISTRY/my-spring-app:$IMAGE_TAG
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          repository: SSG-Donkey/k8s-manifest-repo
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: k8s-manifest-repo

      - name: Update Kubernetes resources
        run: |
          kustomize edit set image demo-testrepo/my-spring-app=${{ steps.login-ecr.outputs.registry }}/demo-testrepo/my-spring-app:${{ github.sha }}
          cat kustomization.yaml
        working-directory: ./k8s-manifest-repo/overlays/dev

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name eks-demo --region ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      # 추가할 수 있는 임시적인 오류 회피 방법
      - name: Apply Kubernetes resources with validation disabled
        run: |
          kubectl apply -f . --validate=false
        working-directory: ./k8s-manifest-repo/overlays/dev

      - name: Commit files
        run: |
          git config --global user.email "dkehdrn@naver.com"
          git config --global user.name "namjyung"
          git add .
          git commit -m "Update image tag for board-app"
          git push
        working-directory: ./k8s-manifest-repo

env:
  ECR_REGISTRY: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-testrepo
  IMAGE_TAG: latest
