name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./backend/gradlew

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew build
        
      - name: Build Docker image
        run: |
          cd ./backend/
          docker build -t my-spring-app .
      
      - name: Tag Docker image
        run: |
          docker tag my-spring-app:latest $ECR_REGISTRY/my-spring-app:$IMAGE_TAG
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/my-spring-app:$IMAGE_TAG

env:
  ECR_REGISTRY: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-testrepo
  IMAGE_TAG: latest

